
CREATE OR REPLACE TYPE mares_Type force as object (
  MR_HOTEL           VARCHAR2(2 BYTE),
  MR_RESERVA         VARCHAR2(12 BYTE),
  MR_MAYORISTA       VARCHAR2(8 BYTE),
  MR_AGENCIA         VARCHAR2(8 BYTE),
  MR_GRUPO           VARCHAR2(6 BYTE),
  MR_PAIS            VARCHAR2(3 BYTE),
  MR_CODPOS          VARCHAR2(7 BYTE),
  MR_TIPO_HUESPED    VARCHAR2(2 BYTE),
  MR_VIP             VARCHAR2(1 BYTE),
  MR_LLEGADA         DATE,
  MR_SALIDA          DATE,
  MR_NOCHES          NUMBER(3),
  MR_LLEGADA_H       VARCHAR2(5 BYTE),
  MR_VUELO           VARCHAR2(10 BYTE),
  MR_LINEA           VARCHAR2(4 BYTE),
  MR_TIPO_HAB        VARCHAR2(6 BYTE),
  MR_ADULTO          NUMBER(1),
  MR_MENOR           NUMBER(1),
  MR_BEBE            NUMBER(1),
  MR_PLAN_1          VARCHAR2(3 BYTE),
  MR_PLAN_2          VARCHAR2(3 BYTE),
  MR_PAQUETE         VARCHAR2(5 BYTE),
  MR_SERVICIO        VARCHAR2(1 BYTE),
  MR_NOTAS           VARCHAR2(100 BYTE),
  MR_STATUS          VARCHAR2(1 BYTE),
  MR_TARIFA          VARCHAR2(2 BYTE),
  MR_IMPORTE         NUMBER(14,2),
  MR_DEPOSITO        NUMBER(7,2),
  MR_APELLIDO_1      VARCHAR2(20 BYTE),
  MR_NOMBRE_1        VARCHAR2(20 BYTE),
  MR_APELLIDO_2      VARCHAR2(20 BYTE),
  MR_NOMBRE_2        VARCHAR2(20 BYTE),
  MR_APELLIDO_3      VARCHAR2(20 BYTE),
  MR_NOMBRE_3        VARCHAR2(20 BYTE),
  MR_APELLIDO_4      VARCHAR2(20 BYTE),
  MR_NOMBRE_4        VARCHAR2(20 BYTE),
  MR_MAYORISTA_CUN   VARCHAR2(3 BYTE),
  MR_HABI            VARCHAR2(6 BYTE),
  MR_VOUCHER         VARCHAR2(20 BYTE),
  MR_RESERVA_P       VARCHAR2(12 BYTE),
  MR_HOTEL_ORIG      VARCHAR2(2 BYTE),
  MR_CAP_F           DATE,
  MR_CAN_F           DATE,
  MR_MOD_F           DATE,
  MR_SEMAFORO        VARCHAR2(1 BYTE),
  MR_NOTAS_HOTEL     VARCHAR2(30 BYTE),
  MR_NOTAS_CENTRAL   VARCHAR2(30 BYTE),
  MR_SOURCE          VARCHAR2(2 BYTE),
  MR_AGENCY_CONF     VARCHAR2(16 BYTE),
  MR_MONEDA          VARCHAR2(3 BYTE),
  MR_JUNIOR          NUMBER(1),
  MR_TIPO_VENTA      VARCHAR2(10 BYTE),
  MR_CATEGORIA       VARCHAR2(5 BYTE),
  MR_CODIGO_MAESTRO  VARCHAR2(12 BYTE),
  MR_CANTIDAD_CAMAS  NUMBER(4),
  MR_EMAIL           VARCHAR2(640 BYTE),
  MR_EVENTO          VARCHAR2(30 BYTE),
  MR_CHANNEL_TEXT    VARCHAR2(4000 BYTE),
  MR_PROMO           VARCHAR2(30 BYTE),
  MR_RATE_PER_NIGHT  varchar2(1024),
  constructor function mares_type  (
          MR_HOTEL           VARCHAR2 default null,
          MR_RESERVA         VARCHAR2 default null,
          MR_MAYORISTA       VARCHAR2 default null,
          MR_AGENCIA         VARCHAR2 default null,
          MR_GRUPO           VARCHAR2 default null,
          MR_PAIS            VARCHAR2 default null,
          MR_CODPOS          VARCHAR2 default null,
          MR_TIPO_HUESPED    VARCHAR2 default null,
          MR_VIP             VARCHAR2 default null,
          MR_LLEGADA         DATE   default null,
          MR_SALIDA          DATE default null,
          MR_NOCHES          NUMBER default null,
          MR_LLEGADA_H       VARCHAR2 default null,
          MR_VUELO           VARCHAR2 default null,
          MR_LINEA           VARCHAR2 default null,
          MR_TIPO_HAB        VARCHAR2 default null,
          MR_ADULTO          NUMBER default null,
          MR_MENOR           NUMBER default null,
          MR_BEBE            NUMBER default null,
          MR_PLAN_1          VARCHAR2 default null,
          MR_PLAN_2          VARCHAR2 default null,
          MR_PAQUETE         VARCHAR2 default null,
          MR_SERVICIO        VARCHAR2 default null,
          MR_NOTAS           VARCHAR2 default null,
          MR_STATUS          VARCHAR2 default null,
          MR_TARIFA          VARCHAR2 default null,
          MR_IMPORTE         NUMBER default null,
          MR_DEPOSITO        NUMBER default null,
          MR_APELLIDO_1      VARCHAR2 default null,
          MR_NOMBRE_1        VARCHAR2 default null,
          MR_APELLIDO_2      VARCHAR2 default null,
          MR_NOMBRE_2        VARCHAR2 default null,
          MR_APELLIDO_3      VARCHAR2 default null,
          MR_NOMBRE_3        VARCHAR2 default null,
          MR_APELLIDO_4      VARCHAR2 default null,
          MR_NOMBRE_4        VARCHAR2 default null,
          MR_MAYORISTA_CUN   VARCHAR2 default null,
          MR_HABI            VARCHAR2 default null,
          MR_VOUCHER         VARCHAR2 default null,
          MR_RESERVA_P       VARCHAR2 default null,
          MR_HOTEL_ORIG      VARCHAR2 default null,
          MR_CAP_F           DATE default null,
          MR_CAN_F           DATE default null,
          MR_MOD_F           DATE default null,
          MR_SEMAFORO        VARCHAR2 default null,
          MR_NOTAS_HOTEL     VARCHAR2 default null,
          MR_NOTAS_CENTRAL   VARCHAR2 default null,
          MR_SOURCE          VARCHAR2 default null,
          MR_AGENCY_CONF     VARCHAR2 default null,
          MR_MONEDA          VARCHAR2 default null,
          MR_JUNIOR          NUMBER default null,
          MR_TIPO_VENTA      VARCHAR2 default null,
          MR_CATEGORIA       VARCHAR2 default null,
          MR_CODIGO_MAESTRO  VARCHAR2 default null,
          MR_CANTIDAD_CAMAS  NUMBER default null,
          MR_EMAIL           VARCHAR2 default null,
          MR_EVENTO          VARCHAR2 default null,
          MR_CHANNEL_TEXT    VARCHAR2 default null,
          MR_PROMO           VARCHAR2 default null,
          MR_RATE_PER_NIGHT  varchar2 default null
  ) return self as result
)
;
/

CREATE OR REPLACE TYPE BODY mares_type as constructor function mares_type
     (
          MR_HOTEL           VARCHAR2 default null,
          MR_RESERVA         VARCHAR2 default null,
          MR_MAYORISTA       VARCHAR2 default null,
          MR_AGENCIA         VARCHAR2 default null,
          MR_GRUPO           VARCHAR2 default null,
          MR_PAIS            VARCHAR2 default null,
          MR_CODPOS          VARCHAR2 default null,
          MR_TIPO_HUESPED    VARCHAR2 default null,
          MR_VIP             VARCHAR2 default null,
          MR_LLEGADA         DATE   default null,
          MR_SALIDA          DATE default null,
          MR_NOCHES          NUMBER default null,
          MR_LLEGADA_H       VARCHAR2 default null,
          MR_VUELO           VARCHAR2 default null,
          MR_LINEA           VARCHAR2 default null,
          MR_TIPO_HAB        VARCHAR2 default null,
          MR_ADULTO          NUMBER default null,
          MR_MENOR           NUMBER default null,
          MR_BEBE            NUMBER default null,
          MR_PLAN_1          VARCHAR2 default null,
          MR_PLAN_2          VARCHAR2 default null,
          MR_PAQUETE         VARCHAR2 default null,
          MR_SERVICIO        VARCHAR2 default null,
          MR_NOTAS           VARCHAR2 default null,
          MR_STATUS          VARCHAR2 default null,
          MR_TARIFA          VARCHAR2 default null,
          MR_IMPORTE         NUMBER default null,
          MR_DEPOSITO        NUMBER default null,
          MR_APELLIDO_1      VARCHAR2 default null,
          MR_NOMBRE_1        VARCHAR2 default null,
          MR_APELLIDO_2      VARCHAR2 default null,
          MR_NOMBRE_2        VARCHAR2 default null,
          MR_APELLIDO_3      VARCHAR2 default null,
          MR_NOMBRE_3        VARCHAR2 default null,
          MR_APELLIDO_4      VARCHAR2 default null,
          MR_NOMBRE_4        VARCHAR2 default null,
          MR_MAYORISTA_CUN   VARCHAR2 default null,
          MR_HABI            VARCHAR2 default null,
          MR_VOUCHER         VARCHAR2 default null,
          MR_RESERVA_P       VARCHAR2 default null,
          MR_HOTEL_ORIG      VARCHAR2 default null,
          MR_CAP_F           DATE default null,
          MR_CAN_F           DATE default null,
          MR_MOD_F           DATE default null,
          MR_SEMAFORO        VARCHAR2 default null,
          MR_NOTAS_HOTEL     VARCHAR2 default null,
          MR_NOTAS_CENTRAL   VARCHAR2 default null,
          MR_SOURCE          VARCHAR2 default null,
          MR_AGENCY_CONF     VARCHAR2 default null,
          MR_MONEDA          VARCHAR2 default null,
          MR_JUNIOR          NUMBER default null,
          MR_TIPO_VENTA      VARCHAR2 default null,
          MR_CATEGORIA       VARCHAR2 default null,
          MR_CODIGO_MAESTRO  VARCHAR2 default null,
          MR_CANTIDAD_CAMAS  NUMBER default null,
          MR_EMAIL           VARCHAR2 default null,
          MR_EVENTO          VARCHAR2 default null,
          MR_CHANNEL_TEXT    VARCHAR2 default null,
          MR_PROMO           VARCHAR2 default null,
          MR_RATE_PER_NIGHT  varchar2 default null          
    ) return self as result is
     begin
        return;
     end;
end;
/